services:
  - type: web
    name: xss-ctf-web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.web
    buildCommand: ""
    startCommand: ""
    rootDir: .

  - type: worker
    name: admin-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.bot
    buildCommand: ""
    startCommand: |
      while true; do
        php /opt/render/project/src/admin_bot.php
        sleep 60
      done
